default: &default
    adapter: postgresql
    encoding: unicode

development:
    <<: *default
    database: about_me_development

test:
    <<: *default
    database: about_me_test

production:
    <<: *default
    database: about_me_production
    username: about_me
    password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
  